In [4]:
import numpy as np
import copy, math
import matplotlib.pyplot as plt
np.set_printoptions(precision=2)

In [ ]:
# Trying 

In [8]:
X_train = np.array([[2104,5,1,45],[1416,3,2,40],[852,2,1,35]])
y_train = np.array([460,232,178])
print(f"The xtrainig example are :- \n{X_train}")
print(f"The youtputs  are :- \n{y_train}")

The xtrainig example are :- 
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
The youtputs  are :- 
[460 232 178]
